# NOTE: beta version, like my dream about a nearby future :)
# Flake8 runner via Gulp(Node.js)

FROM python:3.7 as flake

# for mounting volumes
RUN mkdir /app

# make docker user
RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo

# # turn off bell
# RUN echo "set bell-style none" >> ~/.inputrc

RUN apt-get update
RUN apt-get install -y python3-dev
# RUN apt-get install -y build-essential python3-dev \
#     python3-setuptools python3-wheel python3-cffi libcairo2 libpango-1.0-0 \
#     libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info

RUN pip install --upgrade pip
RUN pip install --no-cache-dir cython
RUN pip install --no-cache-dir flake8

RUN cd /app
RUN cp /usr/local/bin/flake8 flake8.pyx
RUN cython flake8.pyx --embed -3
RUN gcc -Os -I /usr/include/python3.7m -o flake8 flake8.c -lpython3.7m -lpthread -lm -lutil -ldl
RUN rm flake8.pyx flake8.c

# FROM node:16
#
# COPY --from=flake /usr/local/lib/python3.7/site-packages/ /usr/local/lib/python3.7/site-packages/
# COPY --from=flake /usr/local/bin/ /usr/local/bin/


# RUN apt-get autoremove -y node;\
#     curl -sL https://deb.nodesource.com/setup_14.x | bash -;\
#     apt-get install -y nodejs;\
#     npm i npm@latest -g;\
#     npm i npx@latest -g --force

# RUN npm i -g gulp-cli
#
# WORKDIR /home/docker
# ADD ./package.json ./package.json
# ADD ./gulpfile.js ./gulpfile.js
# RUN npm i
# RUN chown docker:docker package.json
# RUN chown -R docker:docker node_modules
# RUN chown docker:docker gulpfile.js
#
# CMD ["npm", "run", "gulp"]
